In [10]:
import numpy as np

### ARRAY OPERATIONS


#### Arithmetic operations

In [11]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

array([1, 2, 3, 4, 5])

In [17]:
a1+a2
# works ,given both the arrays size are same

In [18]:
a1-a2

array([-5, -5, -5, -5, -5])

In [19]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [20]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [21]:
a1 //a2

array([0, 0, 0, 0, 0])

In [22]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting

In [23]:
l = [10,20,30,40,50]
arr = np.array((l))

In [25]:
arr + 10

array([20, 30, 40, 50, 60])

In [27]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [30]:
# there is no difference between broadcasting and arithmetic operations

#### Deep and Shallow copy

In [32]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
slice = a[:5]
slice = slice * 10

In [ ]:
# whenever we slice in array then there is a deep copy happening

In [38]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
b =a
# as we have not written b=a.copy()  , here shallow copy will be there

In [42]:
b[0]=78

In [43]:
b

array([78,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
a

array([78,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
b = a.copy()

In [46]:
b[0]=1
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
a

array([78,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix operationsm

In [50]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [58]:
A

array([[1, 2],
       [3, 4]])

In [59]:
# For Transpose of a matrix
A.T

array([[1, 3],
       [2, 4]])

In [52]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
# For Matrix multiplication(dot operation ) we use @

In [60]:
A @ B

array([[19, 22],
       [43, 50]])

In [55]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

### Advance Array Manipulation

#### Stacking Array

In [ ]:
# In stacking we have to use VECTORS only , we can't use MATRIX

In [71]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [72]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
np.hstack((a,b))
# It basically joins two array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Splitting Array

In [78]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
np.hsplit(c,2)
# while splitting we have to take care that , we split in equal parts

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [82]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [83]:
a= np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [87]:
a= np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [88]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
