In [2]:
import numpy as np

### NUMPY INDEXING AND SLICING OF VECTORS

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[0]

11

In [8]:
arr[6]

17

In [9]:
arr[9]

20

In [ ]:
''' [11, 12, 13, 14, 15, 16, 17, 18, 19, 20] '''
''' [0  1   2    3   4   5   6   7   8   9] '''  # Indexing

In [10]:
arr[1:5]

array([12, 13, 14, 15])

In [11]:
arr[:5]

array([11, 12, 13, 14, 15])

In [13]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr_slice = arr[3::2]
# it will print the elements which comes after 2 steps not 2 index
arr_slice

array([14, 16, 18, 20])

### NUMPY INDEXING AND SLICING OF MATRIX

In [17]:
arr = np.arange(1,31).reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr[5]
# prints the 5th row

array([26, 27, 28, 29, 30])

In [19]:
arr[0,4]

5

In [21]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [22]:
slice= arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [23]:
arr[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### BOOLEAN INDEXING

In [24]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr % 2 ==0
bool_index

array([ True,  True,  True,  True,  True])

In [29]:
# dont execute this line more than once , as the arr data are already shorten , you have start from start of boolean indexing
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])