In [17]:
import numpy as np

### Basic Array Creation

In [9]:
arr = np.array([1,2,3,4])
# This is an array
arr

array([1, 2, 3, 4])

In [11]:
list_a = [1,2,3,4.6,"string"]
list_a

[1, 2, 3, 4.6, 'string']

In [12]:
np.array(list_a)
# the below output mean that all the data are converted to unicode 32
# basically it converts all different datatype into a same datatype (String)

array(['1', '2', '3', '4.6', 'string'], dtype='<U32')

In [13]:
list_a = [1,2,3,4.6]
np.array(list_a)
# everything converted to float

array([1. , 2. , 3. , 4.6])

In [14]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l
# our list appears as 1-d and called Vector

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
# when we use arrays we get a 2-d view and called MATRIX
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# after 2-d , anything like 3-d,4-d comes under TENSORS

In [21]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr = np.zeros(6)
arr
# creates 1 d

array([0., 0., 0., 0., 0., 0.])

In [24]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [27]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### Array generation funtion

In [35]:
np.random.rand(10)
# the below one is a vector , simple rule if we have one bracket then Vector , if two then Matrix
# random function give values between 0 & 1 ,this is called normalisation


array([0.82587609, 0.11390219, 0.2361925 , 0.4429201 , 0.1448484 ,
       0.80556015, 0.0674819 , 0.01763895, 0.92909856, 0.38823719])

In [36]:
np.random.randn(10)
# for values between 3 & -3 ,this is called standardisation

array([-0.27727397, -0.20298834, -0.80773237, -0.06967531,  0.96091607,
       -0.45571816,  1.07138133, -0.87412856, -0.42623561, -0.2054114 ])

In [37]:
np.random.randint(6)
# gives one random no between 0 & 6

5

In [38]:
np.random.randint(9)
# returns random no between 0 & 9

4

In [39]:
np.random.randint(10,20)

17

In [40]:
np.random.randint(10,20,10)
# generates 10 random no. between 10 ,20 and values can be repeating

array([10, 11, 19, 13, 17, 10, 17, 19, 18, 12])

### Array Attribute

In [ ]:
# Arrtirbutes are variable ,defined inside a class
# Methods are funtion ,defined inside a class

# we call a Methods not Attributes

In [41]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.shape

(3, 3)

In [43]:
arr.size

9

In [44]:
arr.dtype

dtype('int64')

### Array Methods

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.min()

1

In [47]:
arr.max()

9

In [48]:
arr.sum()

45

In [49]:
np.sum(arr,axis=0)
# to get sum for each column

array([12, 15, 18])

In [50]:
np.sum(arr,axis=1)
# to get sum for each row

array([ 6, 15, 24])

In [51]:
arr.mean()

5.0

In [52]:
arr.std()

2.581988897471611

In [53]:
arr.argmax()
# return index of the maximum element

8

In [54]:
arr.argmin()

0

### Reshaping and resizing

In [65]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [66]:
# the below is array reshaping and storing in same arr is resizing
arr = arr.reshape(6,5)

In [67]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])