In [1]:
import numpy as np

#### Valid Sudoku

In [14]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [15]:
s.sum()

405

In [17]:
b = np.sum(s,axis =1)
[b==45]

[array([ True,  True,  True,  True,  True,  True,  True,  True,  True])]

In [20]:
for i in b:
    if i!= 45 :
        print("the sudoku is not valid ")
        break
else:
    print(" it is valid for rows")

 it is valid for rows


In [21]:
c = np.sum(s,axis =0)
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [22]:
for i in c:
    if i!= 45 :
        print("the sudoku is not valid ")
        break
else:
    print(" it is valid for columns")

 it is valid for columns


In [31]:
arr1 = s[:3,:3]

In [34]:
arr2 = s[:3,3:6]
arr2

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [36]:
arr3 = s[:3,6:9]
arr3

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [43]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print("----------")
        print(n)

----------
[[5 3 4]
 [6 7 2]
 [1 9 8]]
----------
[[6 7 8]
 [1 9 5]
 [3 4 2]]
----------
[[9 1 2]
 [3 4 8]
 [5 6 7]]
----------
[[8 5 9]
 [4 2 6]
 [7 1 3]]
----------
[[7 6 1]
 [8 5 3]
 [9 2 4]]
----------
[[4 2 3]
 [7 9 1]
 [8 5 6]]
----------
[[9 6 1]
 [2 8 7]
 [3 4 5]]
----------
[[5 3 7]
 [4 1 9]
 [2 8 6]]
----------
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [44]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


#### General Questions

In [46]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.

In [47]:
data.shape

(5, 3)

In [48]:
#Find the average age of students.

In [50]:
np.mean(data[:,0])

18.4

In [ ]:
#Extract Math marks of all students.

In [61]:
data[:,1]

array([85, 92, 76, 65, 90])

In [52]:
#Find the highest Science mark.

In [62]:
np.max(data[:,2])

95

In [54]:
#Get details of the student who scored more than 90 in Math.

In [63]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [57]:
#Increase Math marks of all students by 5.

In [58]:
data[:,1]+5

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.

In [65]:
data[data[:,0]<19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [ ]:
#Calculate the average marks in each subject (column-wise mean).

In [60]:
np.mean(data[:,1:],axis = 0)

array([81.6, 83.2])

In [ ]:
#Get data of students who scored at least 80 in both subjects.

In [68]:
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.

In [79]:
data1 = data.copy()
print(data1)
data1[:,2][data1[:,2]<75] = 0
data1

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])